Decompile Ghini
zeldaret/tmc pull request #348
Opened 2022-02-03 17:44 UTC by octorock

2022-02-05 05:36 UTC, notyourav requested changes

2022-02-05 05:36 UTC, notyourav commented on src/enemy/ghini.c
> + * @ingroup Objects
```suggestion
 * @ingroup Enemy
```

2022-02-05 05:36 UTC, notyourav commented on src/enemy/ghini.c
> +    if ((u8)(super->action - 8) < 2) {
```suggestion
if (super->action == 8 || super->action == 9) {
```

2022-02-05 05:36 UTC, notyourav commented on src/enemy/ghini.c
> +            if ((u8)(super->action - 1) < 2) {
```suggestion
            if (super->action == 1 || super->action == 2) {
```

2022-02-05 05:36 UTC, notyourav commented on src/enemy/ghini.c
> +        if ((u8)(super->animIndex - 7) < 2) {
```suggestion
        if (super->animIndex == 7 || super->animIndex == 8) {
```

2022-02-05 05:36 UTC, notyourav commented on src/enemy/ghini.c
> +    if (1 < (u8)(super->animIndex - 7)) {
```suggestion
if (super->action != 7 && super->action != 8) {
```

2022-02-05 12:04 UTC, octorock commented on src/enemy/ghini.c
> +    if ((u8)(super->action - 8) < 2) {
Ah, nice

2022-02-06 09:53 UTC, notyourav approved these changes

2022-02-06 09:53 UTC, merged